tracker/announce.go

This code used to work since we could tell if a peer was present in both IP families. We don't have a way to do this now. However, since ba1ad7f5bfadaee6043642bb363c6d7468162a74, it doesn't matter, since line 239 would be hit if `v4seed` or `v6seed` were true and the whole announce will error out.
@jzelinskie does this seem right?

Remove impossible code for 'completed' event

---

tracker/models/models.go

This makes clients with the same IP address, but different ports distinguishable.
I'm pretty sure this doesn't require any changes for PeerMaps.
PTAL

Add Port to PeerKey

---

http/http.go
udp/protocol.go
udp/udp.go

This also makes the format of UDP and HTTP logs a little more similar.

logging: add error to udp logs

---

tracker/announce.go

This assumption was just totally wrong. If there is any kind of packet
loss or the tracker starts up to a pre-existing swarm, all the peers
will get bad request responses.

tracker: rm badrequest when state is unknown

---

udp/protocol.go

This causes packets that have bad connection IDs to not be recorded as a
bad request in our stats. These types of errors to be expected and
should balloon our stats.
Fixes #72.

udp: make BadConnID a normal error

---

Dockerfile

Things have changed a bit, which broke the Docker build. I also moved dependency fetching to before source addition to prevent the dependency cache from being busted when Chihaya source changes.
@jzelinskie

Fix Dockerfile to build with the latest changes

---

stats/mem.go

Adding GC pause metrics to the stats JSON.
Test plan: looked at `/stats` and verified PauseNs is updated properly. The difference in `PauseTotalNs` from one minute to the next is the same as the most recent `PauseNs`.
```
{
"BytesTransmitted": 0,
"Connections.Accepted": 38,
"Connections.Open": 1,
"Memory": {
"Alloc": 534816,
"Frees": 4452,
"HeapAlloc": 534816,
"HeapIdle": 712704,
"HeapInuse": 991232,
"HeapObjects": 803,
"HeapReleased": 0,
"HeapSys": 1703936,
"Lookups": 81,
"Mallocs": 5255,
"PauseNs": 435248,
"PauseTotalNs": 3275305,
"Sys": 3999992,
"TotalAlloc": 995904
},
"Peers.IPv4": {
"Completed": 0,
"Peers": {
"Current": 0,
"Joined": 0,
"Left": 0,
"Reaped": 0
},
"Seeds": {
"Current": 0,
"Joined": 0,
"Left": 0,
"Reaped": 0
}
},
"Peers.IPv6": {
"Completed": 0,
"Peers": {
"Current": 0, …
```

stats: publish last gc PauseNS

---

config/config.go
example_config.json
http/announce_test.go
tracker/tracker.go

This allows for configurable reaping rates and changes the default to
what many public trackers use in the wild.

config: make reaping configurable

---

backend/backend.go
backend/noop/driver.go

Fixes #107 
Note: The gazelle driver will have to be updated as well to implement `backend.Conn`, will do that in a minute

backend: remove unused parameter from LoadAllUsers()

---

tracker/models/models.go

Fixes #94 
Unfortunately we can not just `go fix` the whole project - I found out that `go fix` only fixes new features for the latest release. Using the `fix` from the go version where implicit slice bounds were introduced will probably not work (because it's ancient).

tracker: update reslicing to use implicit slice bounds

---

example_config.json

The string can not be unmarshalled into a `float64`

example config: fixed wrong data type for reapRatio

---

cmd/chihaya/main.go
server/http/config.go
server/http/server.go
server/pool.go
server/store/store.go

This
- fixes config parsing for both the store and the http server
- fixes synchronization when shutting down the pool
- adds a log line indicating the HTTP server has been shut down cleanly
- adds dependencies to cmd/chihaya, so that more shipped modules are built

Hotfix configparse

---

config_example.yaml
server/server.go
server/store/client_store.go
server/store/ip_store.go
server/store/memory/client_store.go
server/store/memory/ip_store.go
server/store/memory/ip_store_test.go
server/store/memory/peer_store.go
server/store/memory/string_store.go
server/store/memory/string_store_test.go
server/store/peer_store.go
server/store/store.go
server/store/string_store.go

- Made it so that all embedded driver/config constructs use the same format (`Name` and `Config`)
- Fixed some error messages/code formatting
- Added easier to debug error messages in case a driver for the store is missing (a driver for what store exactly?)

Config normalize

---

tracker/middleware.go
tracker/tracker.go

If for example the config is invalid, a *MiddlewareConstructor should be able to fail without panicking

tracker: added a way for middleware constructors to fail

---

CONTRIBUTORS
server/http/request.go

Event is an optional key, and if it's invalid or non-existent then it can just be assumed as 'none'.

http: stopped throwing error on invalid event

---

server/store/middleware/response/README.md
server/store/middleware/response/response.go

This commit adds a basic response middlware for both announces, and scrapes.
Completes one of the tasks in #145

middleware: add basic response middleware

---

pkg/bencode/decoder.go
server/http/request.go

Fixes #156.
We could later expand this to make all the current methods in `http/request.go` use `chihaya.Params` and wrap them with a method that specifically uses the `query` package.

more general interfaces

---

chihaya.go
server/http/server.go
server/prometheus/prometheus.go
server/server.go
server/store/memory/peer_store_test.go
server/store/middleware/infohash/blacklist.go
server/store/middleware/infohash/blacklist_test.go
server/store/middleware/infohash/whitelist.go
server/store/middleware/infohash/whitelist_test.go
server/store/store.go
server/store/string_store.go

We are now `golint`, `go vet` and `gosimple` clean.
I also fixed the starting of the prometheus server, simplified the http start/stop methods and implemented some things in the store start/stop methods.
The infohash middleware tests are nicer too.
This fixes #46 for the rewrite.

Lint, vet, Start/Stop

---

config_example.yaml

The example config can now be used without making a change to get a public HTTP tracker.
This assumes #165 to be merged.

config: make example config work

---

.travis.yml

This adds goimports, go vet and golint to travis. It excludes the `/vendor/` directory, just in case we use that at some point.
Good build example:
https://travis-ci.org/mrd0ll4r/chihaya/jobs/131722168
Bad build examples:
https://travis-ci.org/mrd0ll4r/chihaya/jobs/131721602
https://travis-ci.org/mrd0ll4r/chihaya/jobs/131720725
Example with an unclean file in the `/vendor/` directory:
https://travis-ci.org/mrd0ll4r/chihaya/jobs/131720094

travis: add golint, goimports and go vet

---

middleware/varinterval/README.md

Seems someone just copied the deniability README when implementing this.

middleware: fix varinterval README

---

pkg/stopper/stopper.go
server/store/README.md
server/store/ip_store.go
server/store/memory/ip_store.go
server/store/memory/ip_store_test.go
server/store/memory/peer_store.go
server/store/memory/peer_store_test.go
server/store/memory/string_store.go
server/store/memory/string_store_test.go
server/store/middleware/infohash/blacklist.go
server/store/middleware/infohash/blacklist_test.go
server/store/peer_store.go
server/store/store.go
server/store/store_bench.go
server/store/store_tests.go
server/store/string_store.go

This is a WIP for improving  store synchronization, benchmarking and tests.
What was changed:
- The string store is now correctly started/stopped:
- The constructor now accepts a shutdown channel and a wait group in addition to the config
- When the channel is closed, the driver should shut down and notify the wait group
- The store package now has a general string store test that tests according to the interface
- The memory implementation uses that test now
- The store package now has general string store benchmarks, that
- create a new instance of the driver (clean start)
- run a benchmark on it
- close the driver, wait for it to close
- There are two kinds of benchmarks:
- "normal" benchmarks that use the same value over and over again
- "1K" benchmarks that use 1000 different values …

store: add general benchmark and test, add synchronization to string store

---

README.md

These files don't exist or have changed in master, a relative link is needed.

readme: fix broken configuration links

---

chihaya.go
server/store/store_bench.go
server/store/store_tests.go

Added a way to test a PeerStore that omits PeerIDs and fixed some small errors in the tests.

store: fix various small test issues

---

server/store/store_tests.go

I believe that we should not test whatever `AnnouncePeers` returns at all.

store: do not test AnnouncePeers

---

storage/memory/peer_store.go
storage/memory/peer_store_test.go

GC now uses the `PeerLifetime` field.
I added the `<=0` check because that would send the goroutine to spin on the select. I don't really care if people set `PeerLifetime` to zero, may they collect all their peers...

memory: fix garbage collection, add config check

---

frontend/udp/frontend.go
frontend/udp/parser.go
frontend/udp/writer.go

A few fixes:
- the `bytepool` fix: newly created slices had a length of 256, recycled ones had `cap(b)==2048`
- the `t.wg.Wait()` fix: we already wait on `wg` in `Stop()`
- the `handleRequest` signature change: response slice is no longer used
- the `writer` fixes: make it so that the whole response is sent back instead of only the header :)
- some cleanup in the parser

Refactor udp

---

.travis.yml

This should fix the non-failed-but-should-have-failed travis build (https://travis-ci.org/chihaya/chihaya/builds/158065317)
The change in bencode is to see if travis fails now, but it might not use the .travis.yml from the PR. Let's see.

travis: fix swallowing of exit codes in golint loop

---

frontend/http/bencode/bencode.go
frontend/http/bencode/decoder.go
frontend/http/bencode/encoder.go

Go report card runs `gocyclo -n 15`, while trying to reduce the complexity of some of our calls, I noticed that the bencode encoder is ignoring all the errors from calling `Write`. This is fine if you're working with bytes.Buffer or memory, but if you were to use another instance of an io.Writer, it could fail silently.

bencode: add missing error handling

---

example_config.yaml
frontend/http/frontend.go
frontend/udp/frontend.go

This change also adds the missing fields to the example config.
Fixes #228.

frontend: add yaml tags to UDP and HTTP configs

---

Dockerfile

This drastically shrinks the size of the container when deploying using
Quay's squashed image support.
https://docs.quay.io/guides/squashed-images.html

dockerfile: delete the compiler from the container

---

bittorrent/bittorrent.go
example_config.yaml
frontend/http/frontend.go
frontend/http/parser.go
frontend/udp/frontend.go
frontend/udp/parser.go
frontend/udp/writer.go
middleware/hooks.go
middleware/middleware.go
middleware/middleware_test.go
storage/memory/peer_store.go
storage/memory/peer_store_test.go
storage/storage.go
storage/storage_bench.go
storage/storage_tests.go

This adds
1. Benchmarks for hooks. This helps estimate the overhead of our middleware-based approach and to make possible optimizations (i.e. reuse the `AnnounceResponse` struct).
2. An `AddressFamily` field for `Peer`s.
3. A hook that checks a Peer's IP and sets the above field, and also checks numWant.
Also, can a native speaker please tell me whether to name this `sanitationHook` `sanitizationHook` or something else entirely? That'd be great :)
This is about #254 mostly
Results of three benchmark runs on my laptop: (`none` has no middleware at all, just the `AnnounceResponse` alloc, _k_`nop` has _k_ no-op hooks chained, _k_`sanitation` has _k_ sanitation hooks chained)
```
name                         time/op
HookOverhead/none-v4         145ns ± 3%
HookOverhead/none-v6         146ns ± …
```

middleware: add sanitization hook

---

frontend/udp/connection_id.go
frontend/udp/connection_id_test.go
glide.lock
glide.yaml

This adds benchmarks for connection ID generation and verification. Also, the assembly implementation of sha256 improves performance for both by about 500ns (from ~2700ns to ~2200ns).
Click [here](https://github.com/minio/sha256-simd) for the sha256-simd repo.

udp: make connection ID handling faster

---

example_config.yaml

I left the middleware undocumented because I'm not sure what we want to do there.

example_config: add initial documentation

---

bittorrent/bittorrent.go
frontend/http/writer.go
middleware/hooks.go
middleware/middleware.go
storage/memory/peer_store.go

Fixes #280.
Or maybe we should change the `ScrapeResponse` to contain a slice of `Scrape`s and make them contain an `InfoHash`?

udp: fix ordering of scrapes

---

contrib/helm/chihaya/values.yaml

This fixes a bug where the config being used is for HEAD, but previously the container image being used was for a tagged release with a different config schema.

contrib/helm: default to using HEAD container

---

frontend/http/frontend.go
frontend/udp/frontend.go

Fixes #291 
I chose to copy the value out rather than reference it, in case we maybe at some point start to recycle these structs too, who knows.

frontend: fix recording of address family

---

frontend/http/frontend.go
frontend/udp/frontend.go

All ClientErrors are constant and should not cause Prometheus streams to
be generated for all possible failure scenarios in the program.
Fixes #294.

frontend/*: only record ClientErrors to Prometheus

---

frontend/http/parser.go

The default numwant should be used if either the provided numwant is zero or omitted.

Make numwant in http request optional

---

cmd/chihaya/config.go
cmd/chihaya/main.go
frontend/http/frontend.go
frontend/udp/frontend.go
pkg/prometheus/server.go
storage/memory/peer_store.go

This change refactors a bunch of the state of execution into its own
object. It also attempts to simplify stopping and adjusts some other
packages to integrate with the stopper interface.
I think it partially fixes #309.
If you build this and spam SIGUSR1 a lot and quickly (using something like `for i in $(seq 1 30); do kill -SIGUSR1 $(pgrep chihaya); done`), you get a fatal exit along the lines of `listen tcp 0.0.0.0:6881: bind: address already in use` from either the Prometheus server or HTTP frontend. I'm not sure what causes it yet, but most of the time it works.

Refactor root run command

---

bittorrent/bittorrent.go
cmd/chihaya/main.go
frontend/http/frontend.go
frontend/udp/frontend.go
middleware/middleware.go
storage/memory/peer_store.go

```
$ ./chihaya --config example_config.yaml --debug
INFO[0000] enabling debug logging
INFO[0000] starting Prometheus server                    addr="0.0.0.0:6880"
INFO[0000] starting storage                              gcInterval=14m0s peerLifetime=16m0s shardCount=0
INFO[0000] starting middleware                           postHooks=[] preHooks=[]
INFO[0000] starting HTTP frontend                        addr="0.0.0.0:6881" allowIPSpoofing=false readTimeout=5s realIPHeader=x-real-ip tlsCertPath= tlsKeyPath= writeTimeout=5s
INFO[0000] starting UDP frontend                         addr="0.0.0.0:6881" allowIPSpoofing=false maxClockSkew=10s privateKey="paste a random string here that will be used to hmac connection IDs"
DEBU[0011] generated scrape response …
```

middleware: add structured logging to logic

---

example_config.yaml
storage/memory/peer_store.go

@jzelinskie your logging of config values brought this up. Apparently our example config was wrong the whole time ¯\\_(ツ)_/¯
Qualitative `tbomb` benchmark on my laptop:
Before, 1024 shards configured, actually using one shard:
```
Dispatching 200 clients
Waiting for results...
Requests:                           578724
Successful requests:                578535
failed requests:                       189
Connect attempts:                      200
Failed connects:                         0
Successful requests rate:            57851 hits/sec
Approximate concurrency:            200.00 clients running
Test time:                           10.00 sec
Errors encountered:
```
After, actually 1024 shards:
```
Dispatching 200 clients
Waiting for results...
Requests:                           641252 …
```

storage/config: fix example config, add warning for missing shardCount

---

example_config.yaml
storage/memory/peer_store.go
storage/memory/peer_store_test.go

This adds precise metrics about the number of leechers and seeders to the memory implementation.
This is a pretty big performance hit, maybe we should make it optional? What also annoys me and should maybe be fixed long term is that prometheus uses `float64` for everything (and does expensive floating-point math on these integers). Maybe we can implement something, prometheus only relies on interfaces.
Benchmark:
```
benchmark                               old ns/op     new ns/op     delta
BenchmarkPut                            396           435           +9.85%
BenchmarkPut1k                          399           505           +26.57%
BenchmarkPut1kInfohash                  470           507           +7.87%
BenchmarkPut1kInfohash1k                470           512           +8.94% …
```

storage: add prometheus metrics for seeders/leechers

---

cmd/chihaya/config.go
cmd/chihaya/main.go

Replace logging memory addresses with actual hook names.
Closes #317

cmd/chihaya: log hook names on startup

---

storage/memory/peer_store.go

When left blank in the config, the default prometheus_reporting_interval value
defaulted to 0, causing a panic during peer store initialization. This
change sets the default value to 1 if not provided.

storage/memory: set default prometheus_reporting_interval

---

middleware/jwt/jwt.go

middleware/jwt: escape infohash when debugging

---

cmd/chihaya/main.go
glide.lock
glide.yaml
pkg/log/log.go

This change also moves the logrus library to the lowercase import in
order to avoid breaking downstream projects vendoring chihaya.

glide: update dependencies

---

storage/memory/peer_store_test.go
storage/memorybysubnet/peer_store_test.go

Otherwise we get nasty warnings about using the default value when benchmarking or testing.

storage: add PeerLifetime to test config

---

storage/memorybysubnet/peer_store_test.go

To suppress warnings when benchmarking

storage: update benchmark config

---

pkg/log/log.go

This is useful for benchmarks, mostly, or maybe for log redirection at some point, who knows...

log: add SetOutput function

---

middleware/hooks.go

middleware: document stop.Stopper behaviour for Hooks

---

cmd/chihaya/main.go
cmd/chihaya/signal_unix.go
cmd/chihaya/signal_windows.go

Fixes #302
Also makes it so that logging on windows has coloring disabled by default.
Before:
```
?[36mINFO?[0m[0000] starting Prometheus server                    ?[36maddr?[0m="0.0.0.0:6880"
?[36mINFO?[0m[0000] starting storage                              ?[36mname?[0m=memory
?[36mINFO?[0m[0000] started storage                               ?[36mgcInterval?[0m=3m0s ?[36mname?[0m=memory ?[36mpeerLifetime?[0m=16m0s ?[36mpromReportInterval?[0m=1s ?[36mshardCount?[0m=1024
?[36mINFO?[0m[0000] starting middleware                           ?[36mpostHooks?[0m="[]" ?[36mpreHooks?[0m="[]"
?[36mINFO?[0m[0000] starting HTTP frontend                        ?[36maddr?[0m="0.0.0.0:6881" ?[36mallowIPSpoofing?[0m=true ?[36mdefaultNumWant?[0m=50 ?[36menableRequestTiming?[0m=true ?[36mmaxNumWant?[0m=100 …
```

cmd/chihaya: make things work on windows

---

bittorrent/client_id_test.go
bittorrent/event_test.go
frontend/http/bencode/decoder_test.go
frontend/http/bencode/encoder_test.go
frontend/http/writer_test.go
frontend/udp/connection_id_test.go
frontend/udp/parser_test.go
middleware/varinterval/varinterval_test.go

Because we use testify, this is less useful than normal, but this is
still best practice for table-driven tests.

*: add subtests for all table driven tests

---

cmd/chihaya-e2e/main.go
docs/frontend.md
frontend/udp/frontend.go
frontend/udp/parser.go
frontend/udp/writer.go

Fixes #391 
Turns out we almost already did this - just the responses were mangled.
Also updated docs to indicate we can do both now.
The "old" opentracker IPv6 way has the advantage of having a usable `ip` field in the announce, to enable IP spoofing.

Opentracker v6

---

bittorrent/bittorrent.go
bittorrent/bittorrent_test.go

Fixes #390 
Also adds `String` and `LogFields` methods to `Peer`s.

bittorrent: implement nicer String methods for various types

---

cmd/chihaya/main.go
frontend/http/frontend.go
frontend/udp/frontend.go
middleware/jwt/jwt.go
middleware/logic.go
pkg/prometheus/server.go
pkg/stop/stop.go
storage/memory/peer_store.go
storage/memorybysubnet/peer_store.go

To cleanly support shutting down an HTTP+HTTPS frontend, it is nice to be able to return an array of errors from `Stop()`. It's additionally nice to be able to use a stop group to build this array, i.e. a recursive stop group. See #414 for an example of how the recursion is useful.
This is a developer-facing breaking change; the signature of `stop.Stopper` has changed.

Return []error from Stop() channel, allow recursive stop groups

---

example_config.yaml
frontend/http/frontend.go

Closes #410, by allowing both `addr` and `https_addr` to be set.
Should we add HTTPS to the e2e test suite?
This is a user-facing breaking change; TLS users will need to switch from `addr` to `https_addr`.

Add https_addr config, required to run HTTPS

---

frontend/udp/connection_id.go
frontend/udp/connection_id_test.go
frontend/udp/frontend.go

Benchmarks:
```
BenchmarkNewConnectionID                          	 3000000	      3059 ns/op	    1000 B/op	      14 allocs/op
BenchmarkNewConnectionID-4                        	 1000000	      8192 ns/op	    1000 B/op	      14 allocs/op
BenchmarkNewConnectionIDFromCachedGenerator       	 3000000	      2361 ns/op	     432 B/op	       5 allocs/op
BenchmarkNewConnectionIDFromCachedGenerator-4     	10000000	       779 ns/op	     432 B/op	       5 allocs/op
BenchmarkValidConnectionID                        	 2000000	      3228 ns/op	    1024 B/op	      14 allocs/op
BenchmarkValidConnectionID-4                      	 1000000	      8849 ns/op	    1024 B/op	      14 allocs/op
BenchmarkValidConnectionIDFromCachedGenerator     	 3000000	      2549 ns/op	     464 B/op	       6 allocs/op …
```

frontend/udp: pool connection ID generation state

---

cmd/chihaya/config.go
example_config.yaml
middleware/torrentapproval/torrentapproval.go
middleware/torrentapproval/torrentapproval_test.go

this makes it possible to specify a torrent whitelist/blacklist in the
configuration file based on their hexadecimal hash.
Fixes #375

middleware : add torrent approval package

---

Dockerfile

Without this in the runtime image, anything that makes outgoing HTTPS connections will fail (e.g. the JWT middleware).

dockerfile: add CA certificates

---

README.md

- Facebook no longer use the code that is on HEAD
- Chihaya should not incorrectly state that we do and mislead the general public

Remove Facebook from README.md

---

.travis.yml
Dockerfile
README.md
dist/example_config.yaml
dist/travis/check.sh
dist/travis/config_memory.yaml
dist/travis/config_redis.yaml
dist/travis/install_reproducible.sh
dist/travis/install_tip.sh
docs/storage/redis.md

Fixes #446 
Maybe we should think about putting our build script into an actual script and call that with, like, one parameter that specifies whether or not we want vendored dependencies, because it's getting quite big...

travis: add e2e tests with redis storage

---

frontend/http/frontend.go

Since Content-Type is not explicitly set, golang sniffs the responses
and attempts a guess. With announce responses, this usually means it
guesses application/octet-stream.
According to the godoc at
https://golang.org/pkg/net/http/#ResponseWriter
// If WriteHeader has not yet been called, Write calls
// WriteHeader(http.StatusOK) before writing the data. If the Header
// does not contain a Content-Type line, Write adds a Content-Type set
// to the result of passing the initial 512 bytes of written data to
// DetectContentType. Additionally, if the total size of all written
// data is under a few KB and there are no Flush calls, the
// Content-Length header is added automatically.

http: explicitly set Content-Type header

---

bittorrent/params.go
dist/example_config.yaml
dist/travis/config_memory.yaml
dist/travis/config_redis.yaml
frontend/http/frontend.go

Update to allow arrays of routes to be passed to the http frontend.
This also supports named parameters as permitted by the
router.
To avoid external dependencies in the middleware, a RouteParam and
RouteParams type was added to the bittorrent package.
Note: this eliminates the need for "enable_legacy_php_urls", as
the the additional route could be added to the route array. However,
this may be considered a breaking change.

http: allow for customized routes

---

.github/workflows/go.yaml
README.md

The link and image source were reversed by accident.

readme: fix broken build status badge

---

.github/workflows/CI.yaml

Because dependabot creates branches on the origin repository, it triggers a CI run for both "push" and "pull request" unless this patch is applied.

.github/workflows: only run dependabot CI on PR

---

cmd/chihaya/signal_windows.go

Single line change, similar as in https://github.com/chihaya/chihaya/commit/129aac23
Unit tests passed on my Windows machine:
```
PS C:\Users\xxx\chihaya> go test $(go list ./...)       
ok      github.com/chihaya/chihaya/bittorrent   0.134s
?       github.com/chihaya/chihaya/cmd/chihaya  [no test files]
?       github.com/chihaya/chihaya/frontend     [no test files]
ok      github.com/chihaya/chihaya/frontend/http        0.091s
ok      github.com/chihaya/chihaya/frontend/http/bencode        0.057s
ok      github.com/chihaya/chihaya/middleware   0.092s [no tests to run]
?       github.com/chihaya/chihaya/middleware/jwt       [no test files]
ok      github.com/chihaya/chihaya/middleware/pkg/random        0.086s
ok      github.com/chihaya/chihaya/middleware/torrentapproval   0.101s
ok …
```

Remove unused import 'os/signal' for windows

---

cmd/chihaya/main.go
frontend/frontend.go
frontend/udp/bytepool/bytepool.go
middleware/varinterval/varinterval.go
pkg/metrics/server.go
storage/redis/peer_store.go
storage/storage.go

Short package docs makes the linter warnings happy, so it becomes easier to see what is really going on. Then, there is a fix for a potential attack on the Prometheus endpoint, also reported by CI.
On my fork this is now [green](https://github.com/contribforks/chihaya/actions/runs/4075701092), lets see what happens here.

ci: fix lint, add docs

---

pkg/metrics/server.go

fixes prometheus metrics server not answering requests due to misconfigured timeout

prometheus: fix metrics server
