http/query/query.go, http/query/query_test.go
=> Fix panic occurring when blank query params are present

chihaya.go, debug.go
To help track down #65. The way you use this is:
```
chihaya -debug localhost:6060
```
and then
```
go tool pprof http://localhost:6060/debug/pprof/heap
```
@jzelinskie @dtrackd
=> Add pprof debug HTTP endpoint

tracker/announce.go
A peer can join a swarm immediately as completed if they already have
the file before they ever announce. If we don't have them in our
leechers, we were previously failing to add them as a seeder.
=> tracker: remove last "bad request"

http/tracker.go
The remote port used to send the announce has nothing to do with the
port being listened to for the torrent client protocol.
=> http: stop using remote http port

tracker/announce.go
520a357 inadvertently changed the logic on how many times
leecherFinished was being called and recording completion events to the
stats. This commit makes this that clearer and avoids over incrementing
the number of Seeders in our stats.
=> tracker: fix logic recording complete events

.travis.yml, README.md
No idea if this is going to pass the builds, but this is probably what we should target.
=> travis: update to Go 1.5

udp/udp.go
Fixes #108 
I'm pretty sure this works, but there are no tests checking that, are there?
=> udp: replace boolean-synchronization with channels

CONFIGURATION.md
The explanations are, let's call it a guideline. Bear in mind I'm not a native speaker, so feel free to fix any mistakes ;-)
=> documentation: fixed JSON capitalization in CONFIGURATION.md, added missing keys

chihaya.go, server/http/request.go, server/store/memory/client_store.go, server/store/memory/peer_store.go
Various things from the comments.
=> Middleware smallfixes

CONTRIBUTORS, cmd/chihaya/main.go, config/example.yaml, server/store/client_store.go, server/store/ip_store.go, server/store/memory/ip_store.go, server/store/memory/ip_store_test.go, server/store/middleware/ip/README.md, server/store/middleware/ip/blacklist.go, server/store/middleware/ip/whitelist.go, server/store/peer_store.go, server/store/store.go
- Added an IPStore 
- Removed unnecessary `name` parameter for Open(Client|Peer|IP)Store
- Made it so that (Client|Peer|IP)Stores are opened
- Added myself to the CONTRIBUTORS
- Added IP blacklist/whitelist middlewares
=> IP store, middlewares

server/store/middleware/ip/README.md
=> doc: fixed IP blacklist/whitelist middleware documentation capitalization

server/store/client_store.go, server/store/memory/client_store.go, server/store/middleware/client/README.md, server/store/middleware/client/blacklist.go, server/store/middleware/client/whitelist.go
Added client middlewares, fixed ClientStore to use `chihaya.PeerID`s for lookup
=> Client middlewares

config_example.yaml, server/store/memory/string_store.go, server/store/memory/string_store_test.go, server/store/store.go, server/store/string_store.go
One step at a time, just adding the StringStore for now.
I thought about adding/checking/removing not the complete string, but rather a prefix plus the data - this would allow us to have smaller locks, if that makes sense...
=> store: added StringStore

config.go, config_example.yaml, tracker/middleware.go, tracker/tracker.go
This is my take on configuring middlewares.
=> middleware: made middleware configurable

cmd/chihaya/main.go, middleware/deniability/README.md, middleware/deniability/config.go, middleware/deniability/config_test.go, middleware/deniability/deniability.go, middleware/deniability/deniability_test.go, pkg/random/peer.go, pkg/random/peer_test.go, pkg/random/string.go, pkg/random/string_test.go
=> Deniability middleware, some util packages

cmd/chihaya/main.go, server/store/middleware/infohash/README.md, server/store/middleware/infohash/blacklist.go, server/store/middleware/infohash/blacklist_test.go, server/store/middleware/infohash/config.go, server/store/middleware/infohash/config_test.go, server/store/middleware/infohash/whitelist.go, server/store/middleware/infohash/whitelist_test.go, tracker/middleware.go, tracker/middleware_test.go, tracker/tracker.go
=> middleware: added infohash middleware 

cmd/chihaya/main.go, middleware/varinterval/README.md, middleware/varinterval/config.go, middleware/varinterval/config_test.go, middleware/varinterval/varinterval.go, middleware/varinterval/varinterval_test.go
=> middleware: added varinterval

chihaya.go, chihaya_test.go, middleware/varinterval/varinterval_test.go, server/store/memory/peer_store.go, server/store/memory/peer_store_test.go
A non-pointer receiver and parameter make more sense to me.
Also formatted some stuff.
=> make peer Equal work on values

server/store/memory/peer_store.go
This applies the optimization I discovered in #50 to our `memory` implemetation.
Benchmark:
```
benchmark                                                            old ns/op     new ns/op     delta
BenchmarkPeerStore_PutSeeder-8                                       808           685           -15.22%
BenchmarkPeerStore_PutSeeder1KInfohash-8                             925           730           -21.08%
BenchmarkPeerStore_PutSeeder1KSeeders-8                              835           746           -10.66%
BenchmarkPeerStore_PutSeeder1KInfohash1KSeeders-8                    816           660           -19.12%
BenchmarkPeerStore_PutDeleteSeeder-8                                 2438          2160          -11.40%
BenchmarkPeerStore_PutDeleteSeeder1KInfohash-8                       2644 …
```
=> memory: optimize peer store memory footprint and performance

server/store/memory/peer_store.go
The last PR about this was not up to date. Sorry about that
=> fix memory optimization

server/store/memory/peer_store.go
Removing `defer`s whenever not too inconvenient:
```
benchmark                                                            old ns/op     new ns/op     delta
BenchmarkPeerStore_PutSeeder-8                                       894           890           -0.45%
BenchmarkPeerStore_PutSeeder1KInfohash-8                             1164          758           -34.88%
BenchmarkPeerStore_PutSeeder1KSeeders-8                              941           766           -18.60%
BenchmarkPeerStore_PutSeeder1KInfohash1KSeeders-8                    1160          946           -18.45%
BenchmarkPeerStore_PutDeleteSeeder-8                                 3479          3918          +12.62%
BenchmarkPeerStore_PutDeleteSeeder1KInfohash-8                       3315          3142          -5.22% …
```
=> memory: optimize peer store performance

server/store/memory/ip_store_test.go, server/store/memory/string_store_test.go
Only cosmetic changes, but  might prove useful if any of them get a configuration in the future.
=> memory: clean up tests

README.md
Sorry that this branch is off of upstream -- I made the commit on the GitHub website and not on a dev machine.
=> readme: add architecture section

cmd/chihaya/main.go
Some cleaning up and fixes here and there.
I made a separate channel for signals, otherwise we could close it and send a signal on it while we are shutting down which would then panic.
=> cmd/chihaya: clean up

cmd/chihaya/config.go, cmd/chihaya/main.go
...wow the diff sucks for this. I basically just pulled the closure out into its own function that returns an error and then moved the config stuff into its own file.
=> cmd: pull closure out into its own func and add config.go

frontend/http/writer.go
This is #189 for the refactor branch.
=> http: fix encoding of IPv4 peers with 16-byte addresses

Dockerfile, glide.lock, glide.yaml
They need docs, but for now this is fine.
=> add Dockerfile and Glide

CONTRIBUTORS, README.md, bittorrent/params_test.go, stopper/stopper.go
...and fix some things it found
=> add goreportcard badge

README.md
I have to say: it's awesome being able to see a diff of the diagrams!
=> readme: update diagram

bittorrent/bittorrent.go, frontend/http/frontend.go, frontend/udp/frontend.go, frontend/udp/writer.go, middleware/hooks.go, middleware/middleware.go
This has both the final middleware for pre hooks (response) and post hooks (swarm interaction).
CI will fail, requires #220.
=> Final middleware

cmd/chihaya/main.go, middleware/jwt/jwt.go, middleware/middleware.go
=> cmd/chihaya: stop hooks

cmd/chihaya/config.go, middleware/jwt/jwt.go
=> jwt: add updateKeys method and call in constructor

frontend/http/parser.go
=> http: fix IPv4 addresses not 4 bytes long

middleware/hooks.go, storage/storage.go
=> storage: react correctly to ErrDNE for announces

tracker/jwt.go
These were previously raising a 500 in the HTTP server; rather, they
should return 200 but explain the the client that their JWTs are
invalid.
=> jwt: verifying JWT are now client errors

frontend/http/bencode/encoder.go, frontend/http/bencode/encoder_test.go
=> http/bencode: add missing []Dict case

middleware/hooks.go
This change adjusts it such that only empty Swarms return the request
Peer. This also increments the Scrape data properly if a peer is added.
Fixes #241.
=> middleware: fix scrape data in announces

frontend/udp/frontend.go, frontend/udp/parser.go
=> udp: fix IP bytes not being copied out of the packet

cmd/chihaya/config.go
=> Fix configure file parse

bittorrent/params.go
=> bittorrent: invalid infohash -> ClientError

storage/memory/peer_store_test.go, storage/storage_tests.go
This tests against the interface. Gets us to ~70% coverage for the memory implementation (the big part missing is `collectGarbage`).
=> storage: add TestPeerStore test

cmd/chihaya/main.go
I made this a SIGUSR1 instead of a SIGHUP. I know I know, many things use SIGHUP for this kind of stuff, but I think that's because there was nothing else when they were written. We have user-defined signals now, so why not use them?
Fixes #215
=> cmd/chihaya: add config reloading via SIGUSR1

pkg/prand/prand.go, pkg/prand/prand_test.go
I need this for the deniability and varinterval middleware to be able to handle multiple requests in parallel.
=> prand: add Container

middleware/jwt/jwt.go, middleware/middleware.go, pkg/stopper/stopper.go, storage/storage.go
This also adds a package docs for the stopper package.
=> stopper: move to pkg package

frontend/http/frontend.go
=> http: fix prometheus timings

frontend/http/frontend.go, frontend/udp/frontend.go
=> frontend/udp: rm copypasta metric recording

storage/memory/peer_store.go
The simplest statistics for the memory implementation.
I wonder if it'd be better to record these asynchronously in a designated goroutine?
Benchmark changes:
```
benchmark                                 old ns/op     new ns/op     delta
BenchmarkPut                              350           347           -0.86%
BenchmarkPut-8                            565           550           -2.65%
BenchmarkPut1k                            379           386           +1.85%
BenchmarkPut1k-8                          602           627           +4.15%
BenchmarkPut1kInfohash                    397           404           +1.76%
BenchmarkPut1kInfohash-8                  106           114           +7.55%
BenchmarkPut1kInfohash1k                  400           416           +4.00% …
```
=> storage: add prometheus to memory implementation

README.md, example_config.yaml
=> README: update development section

contrib/helm/chihaya/.helmignore, contrib/helm/chihaya/Chart.yaml, contrib/helm/chihaya/templates/NOTES.txt, contrib/helm/chihaya/templates/_helpers.tpl, contrib/helm/chihaya/templates/configmap.yaml, contrib/helm/chihaya/templates/deployment.yaml, contrib/helm/chihaya/templates/service.yaml, contrib/helm/chihaya/values.yaml, example_config.yaml, frontend/udp/frontend.go
This makes it possible for you to deploy Chihaya on Kubernetes in 2 commands:
```sh
$ helm package contrib/helm/chihaya
$ helm install chihaya-0.1.0.tgz
```
=> initial helm package

example_config.yaml, frontend/http/frontend.go
=> frontend/http: add TLS support

contrib/helm/chihaya/values.yaml, example_config.yaml, middleware/hooks.go, middleware/middleware.go
=> middleware: sanitize max scrape infohashes

middleware/jwt/jwt.go, middleware/middleware.go, pkg/stop/stop.go, storage/storage.go
This makes most of the callsites stutter slightly less.
¯\_(ツ)_/¯
=> mv pkg/stopper pkg/stop

bittorrent/params.go
=> bittorrent: make ParseURLData return ClientErrors

cmd/chihaya/main.go
This also updates PreRuns to return their errors.
=> cmd/chihaya: move cpuprofile into postrun

example_config.yaml, frontend/http/frontend.go, frontend/udp/frontend.go, storage/memory/peer_store.go
Before merging, I want to check what this does to our metrics.
Still, gives me a few hundred more reqs/s on a linux machine, and here are some storage benchmarks:
```
benchmark                                 old ns/op     new ns/op     delta
BenchmarkPut-2                            410           361           -11.95%
BenchmarkPut-4                            487           455           -6.57%
BenchmarkPut1k-2                          517           394           -23.79%
BenchmarkPut1k-4                          521           486           -6.72%
BenchmarkPut1kInfohash-2                  276           266           -3.62%
BenchmarkPut1kInfohash-4                  138           134           -2.90%
BenchmarkPut1kInfohash1k-2                279           267           -4.30% …
```
=> Remove most calls to time.Now

cmd/chihaya/config.go, cmd/chihaya/main.go, docs/storage/memorybysubnet.md, example_config.yaml, storage/memory/peer_store.go, storage/memorybysubnet/peer_store.go, storage/memorybysubnet/peer_store_test.go, storage/storage.go
This is a WIP branch attempting to fix #267.
=> Storage Drivers (starting w/ subnet memory)

middleware/jwt/jwt.go, storage/memory/peer_store.go, storage/memorybysubnet/peer_store.go, storage/prometheus.go
...this also adds improved debug logging to the JWT middleware, which was my original intention, lol.
=> Fix panic on binary start

frontend/frontend.go, frontend/http/frontend.go, frontend/udp/frontend.go, middleware/middleware.go
=> TrackerLogic returns modified Contexts

middleware/jwt/jwt.go
This avoids some corner-cases that can be experienced when trying to
url-escape raw bytes.
=> middleware/jwt: encode infohashes as hex

bittorrent/params.go, bittorrent/params_test.go
Fixes #337 
Fixes #326 
Makes URL parsing about 15% faster on my machine:
```
BenchmarkParseQuery       	 2000000	      2016 ns/op	     387 B/op	       3 allocs/op
BenchmarkParseQuery       	 2000000	      2013 ns/op	     387 B/op	       3 allocs/op
BenchmarkParseQuerySimple 	 3000000	      1707 ns/op	     387 B/op	       3 allocs/op
BenchmarkParseQuerySimple 	 3000000	      1703 ns/op	     387 B/op	       3 allocs/op
BenchmarkURLParseQuery    	 2000000	      1852 ns/op	     463 B/op	       7 allocs/op
BenchmarkURLParseQuery    	 2000000	      1847 ns/op	     463 B/op	       7 allocs/op
```
`ParseQuery` is what we had before, `ParseQuerySimple` is this (a simplification of `url.parseQuery`), `URLParseQuery` is `url.ParseQuery`.
=> Fix parsing

example_config.yaml, storage/memory/peer_store.go, storage/memorybysubnet/peer_store.go
Some cleanup, probably more sane defaults.
Fixes #341
=> storage: update config defaults

storage/memory/peer_store.go, storage/memory/peer_store_test.go, storage/memorybysubnet/peer_store.go, storage/memorybysubnet/peer_store_test.go, storage/storage_bench.go
=> storage: add Benchmarks for ScrapeSwarm, optimize implementations

cmd/chihaya/main.go
=> cmd/chihaya: log which config is in  use

frontend/http/frontend.go
=> http: add default ReadTimeout, WriteTimeout

frontend/udp/connection_id.go, frontend/udp/frontend.go, pkg/timecache/timecache.go, pkg/timecache/timecache_test.go, storage/memory/peer_store.go, storage/memorybysubnet/peer_store.go
=> Timecache: cache time

example_config.yaml, frontend/http/frontend.go
=> http: add option for legacy PHP URLs

storage/storage.go, storage/storage_tests.go
=> storage: document PeerStore in more  detail

frontend/udp/frontend.go
=> udp: set address family for connect metrics

example_config.yaml, middleware/middleware.go
Fixes #365 
Turns out this is not in the official spec, but in the wiki.theory.org description of the protocol...
=> middleware, config: re-add support for min interval

docs/frontend.md
=> docs: add frontend documentation

.travis.yml, Dockerfile, README.md
Totally forgot about these references.
Reminder to always `git grep` before merging!
=> *: remove glide from README & Dockerfile

.travis.yml, Gopkg.lock, Gopkg.toml, cmd/chihaya-e2e/README.md, cmd/chihaya-e2e/main.go
Example travis log [looks a little cluttered](https://travis-ci.org/chihaya/chihaya/jobs/324691145) but seems to work.
Fixes #151
=> travis: add chihaya e2e testing

Dockerfile, cmd/chihaya-e2e/main.go, example_config.yaml
=> *: move default tracker port to 6969

bittorrent/sanitize.go
=> Validate port

frontend/http/frontend.go
=> http: fix TLS

.travis.yml, Gopkg.lock, Gopkg.toml, cmd/chihaya-e2e/README.md, cmd/chihaya/e2e.go, cmd/chihaya/main.go
This change unifies chihaya and chihaya-e2e binaries.
It also vendors the code missing from the project that was used in
chihaya-e2e.
Fixes #402.
=> cmd: add e2e command

dist/helm/chihaya/values.yaml, example_config.yaml, frontend/http/frontend.go
=> Add config to enable keepalive/persistent connections

frontend/http/parser.go
=> frontend/http: canonicalize http real_ip_header

cmd/chihaya/config.go, frontend/udp/connection_id.go, frontend/udp/connection_id_test.go, middleware/clientapproval/clientapproval.go, middleware/jwt/jwt.go, middleware/middleware.go, middleware/torrentapproval/torrentapproval.go, middleware/varinterval/varinterval.go, storage/memory/peer_store.go, storage/memorybysubnet/peer_store.go
=> fix goimports error

frontend/http/frontend.go
=> split listen&serve for http

README.md
We never got format approval for anything here, so I think we'd all feel
more comfortable not including it.
=> readme: remove endorsements

example_config.yaml, frontend/http/frontend.go, frontend/http/parser.go, frontend/udp/frontend.go, frontend/udp/parser.go
Fixes #443
Probably doesn't build yet because of the formatting of `cmd/chihaya/config.go`.
=> Frontend defaults

bittorrent/params.go
Add a helper method to the RouteParams to retrieve a value by name
=> add helper method to retrieve RouteParam by name

.github/FUNDING.yml
This adds a sponsor GitHub link
=> github: init funding

pkg/log/log.go
This should help a lot for debugging new errors.
=> pkg/log: add type field for errors

.github/dependabot.yml
=> .github: fix yaml indentation

README.md
=> README: refresh badges & move release disclaimer
